### PR TITLE
German Translation added

### PR DESCRIPTION
**Pull request by eag75**
Hello Daniele Rolli,

I have added a German translation to your Beaver Notes project. Thanks for your good and detailed instructions on the project page, that made it a lot easier for me.

This is my first pull request here on Github, if you want me to change anything, please let me know.

I'm really looking forward to your iOS/Android version of your app and would be happy to contribute the corresponding translation.

Best regards
Danny Schellnock

### CODE REVIEW

**Comment by Daniele-rolli** [comment]
Hi Danny Schellnock,

Thank you for your assistance in translating Beaver Notes. I've merged the pull request, as you may have noticed. I will soon release a new version with German language support. Regarding the iOS/Android app, I would greatly appreciate your help with the translation once language support is implemented. I will keep you informed. Thanks for your patience; please be aware that you might need to wait a couple of days before the version of Beaver Notes with German support is published.

Best regards,

Daniele Rolli

**Comment by eag75** [comment]
Hi Daniele,

how exciting, I'm looking forward to testing the new version! 😁

Best regards
Danny

**Comment by Daniele-rolli** [comment]
@all-contributors please add @eag75 for Translation

**Comment by Daniele-rolli** [comment]
hey @eag75, I just wanted to inform you that I've added the following fields to the en.json file, which are part of the pop-up sync reminder featured in version 2.5.0, as per the issue. It would be brilliant if you could add the translated fields to the German translation.

```
"index": {
  "syncreminder": "Sync Reminder",
  "syncmessage": "Hey there! Before you start taking notes, please make sure to import your existing notes and export them when you're done to ensure they are synced across all your devices. Happy note-taking!",
  "hide": "Don't show this again"
},
```

```
"settings": {
  "syncreminder": "Hide sync reminder"
},
```

**Comment by eag75** [comment]
hey @Daniele-rolli, a quick question. Have you already transferred these changes back to the main branch? Should I better use your develop branch to insert the German translation? 
Greetings 
Danny

**Comment by Daniele-rolli** [comment]
I haven't merged the changes into the main branch yet. It's best if you use the develop branch to ensure a smooth workflow and maintain the main branch in its clean state, as it holds the code for the current version of the app rather than the new one.

**Pull request merged**
